### ISSUE TITLE
Face Detection

### ISSUE THREAD

**Issue by slavakurilyak** [produvia/ai-platform#39]
# Goal(s)

- Detect faces in a photo or video and distinguish them from other objects

# Input(s)

- Photo or video

# Output(s)

- Bounding box around faces

# Objective Function(s)

- TBD

**Comment by hcl14** [comment]
I've cleaned the code of one of the SOTA detector implementations (RetinaFace) https://github.com/hcl14/retinaface-pytorch-inference
