### ISSUE TITLE
Use CNN to classify six signs 0 to 5.

### ISSUE THREAD

**Issue by Shubhambindal2017** [produvia/ai-platform#80]
Network which I will use:
CONV2D -> RELU -> MAXPOOL -> CONV2D -> RELU -> MAXPOOL -> FLATTEN -> FULLYCONNECTED.
I will implement this CNN and use SIGNS dataset representing numbers from 0 to 5. I will use Tensorflow for its implementation. And approximate accuracy which I will get will be around:
train accuracy : 93-99%
test accuracy : 78-99%

(I got a match on angelList and you asked me to do a coding assignment, so is implementing this model will be sufficient for me to clear coding round?)

**Comment by slavakurilyak** [comment]
@Shubhambindal2017 Please use one pull request: #81
